### ISSUE TITLE
Bug: Ultrawide Monitor Issue

### ISSUE THREAD

**Issue by Xandrice** [solareon/slrn_groups#1]
**Describe the issue**

When you play on an ultrawide (3440x1440 or 21:9 ratio) monitor, they get a scrollbar to the right of their screen. 

**Expected behavior**

No scroll bar please :) 

**To Reproduce**

1. Use Ultrawide Monitor
2. Make sure Resolution is 3440x1440 or a 21:9 ratio
3. ensure script or load server
4. log in and see scroll bar

**Media**

![Medal_o6YEKNQXh0](https://github.com/solareon/slrn_groups/assets/48589989/bbad48e6-a4ec-433f-b250-35dec59f734f)

**Needed information (please complete the following information):**
- **Client Version:**: Release
- **Release Version:**: 1.0

**Comment by solareon** [comment]
This will be fixed with the UI rewrite coming "soon"

**Comment by solareon** [comment]
@Xandrice if you have a chance could you test the reworked ui and backend? The debug build is here
https://github.com/solareon/slrn_groups/actions/runs/9734275204/artifacts/1653132477

**Comment by Xandrice** [comment]
@solareon acknowledged - will let you know

**Comment by solareon** [comment]
Fixed
