### ISSUE TITLE
Bug: Created Group Password isn't what was set by group creator

### ISSUE THREAD

**Issue by gZence** [solareon/slrn_groups#6]
**Describe the issue**

When a group is created, no other player can join because other players always received "invalid password", even with correct password that group creator used on group creation. 

**Expected behavior**

Create Group - Give password - Others can join

**To Reproduce**

1. Make Group
2. Give someone else password to join
3. They'll get invalid password
4. Cry

**Media**

If applicable, add a screenshot or a video to help explain your problem.

**Needed information (please complete the following information):**
- **Client Version:**: [e.g. Canary or Release]
- **Release Version:**: [e.g 1.0]

**Additional context**
Add any other context about the issue here.

**Comment by gZence** [comment]
Further testing -> 

group.private.password = password or random.string - is always setting password to random string of 111111's instead of set password.

I changed  random string to 'password' and now all password's work as password, which isnt a bad thing since i have jobs create groups for player on clock in.

**Comment by solareon** [comment]
Please try latest release and see if this is still an issue.
