### ISSUE TITLE
cant make a group 

### ISSUE THREAD

**Issue by gitgaming21** [solareon/slrn_groups#9]
so we just put this on the server to try it out and we keep getting this and im not sure why 
[![image](https://github.com/user-attachments/assets/77dc638c-4427-476d-bda2-0eee5607eabc)](https://cdn.discordapp.com/attachments/1063954322020388924/1267580274124787823/image.png?ex=66a94d9f&is=66a7fc1f&hm=4a50b1e1003df808af01de43d6d19281ffb1297573674f50aee1e36cf4b063c7&)

**Comment by solareon** [comment]
@gitgaming21 are you running the latest ox_lib?

**Comment by gitgaming21** [comment]
no i was just thinking that this was why sorry for that il give that a go

**Comment by solareon** [comment]
Not a problem at all. I'll push a fix with a dependency check for the ox_lib version to help highlight possible issues like this.

**Comment by solareon** [comment]
@gitgaming21 did updating ox_lib fix the issue?
